// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/testr.h"
#include <Rcpp.h>

using namespace Rcpp;

// GetArgs
SEXP GetArgs(SEXP dotsE);
RcppExport SEXP testr_GetArgs(SEXP dotsESEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type dotsE(dotsESEXP );
        SEXP __result = GetArgs(dotsE);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// WriteCapInfo_cpp
void WriteCapInfo_cpp(CharacterVector fname, List args, SEXP retv, SEXP errs, SEXP warns);
RcppExport SEXP testr_WriteCapInfo_cpp(SEXP fnameSEXP, SEXP argsSEXP, SEXP retvSEXP, SEXP errsSEXP, SEXP warnsSEXP) {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< CharacterVector >::type fname(fnameSEXP );
        Rcpp::traits::input_parameter< List >::type args(argsSEXP );
        Rcpp::traits::input_parameter< SEXP >::type retv(retvSEXP );
        Rcpp::traits::input_parameter< SEXP >::type errs(errsSEXP );
        Rcpp::traits::input_parameter< SEXP >::type warns(warnsSEXP );
        WriteCapInfo_cpp(fname, args, retv, errs, warns);
    }
    return R_NilValue;
END_RCPP
}
