// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/testr.h"
#include <Rcpp.h>

using namespace Rcpp;

// SaveArgs
void SaveArgs(SEXP env);
RcppExport SEXP testr_SaveArgs(SEXP envSEXP) {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type env(envSEXP );
        SaveArgs(env);
    }
    return R_NilValue;
END_RCPP
}
// WriteCapInfo_cpp
void WriteCapInfo_cpp(CharacterVector fname);
RcppExport SEXP testr_WriteCapInfo_cpp(SEXP fnameSEXP) {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< CharacterVector >::type fname(fnameSEXP );
        WriteCapInfo_cpp(fname);
    }
    return R_NilValue;
END_RCPP
}
