# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DecorateSubst_cpp <- function(packages, name, functionTypes) {
    .Call('testr_DecorateSubst_cpp', PACKAGE = 'testr', packages, name, functionTypes)
}

UndecorateCpp <- function(name) {
    .Call('testr_UndecorateCpp', PACKAGE = 'testr', name)
}

GetArgs <- function(dotsE) {
    .Call('testr_GetArgs', PACKAGE = 'testr', dotsE)
}

WriteCapInfo_cpp <- function(fname, args, retv, errs, warns) {
    invisible(.Call('testr_WriteCapInfo_cpp', PACKAGE = 'testr', fname, args, retv, errs, warns))
}

