# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GetArgs <- function(dotsE) {
    .Call('testr_GetArgs', PACKAGE = 'testr', dotsE)
}

WriteCapInfo_cpp <- function(fname, args, retv, errs, warns) {
    invisible(.Call('testr_WriteCapInfo_cpp', PACKAGE = 'testr', fname, args, retv, errs, warns))
}

