# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SaveArgs <- function(env) {
    invisible(.Call('testr_SaveArgs', PACKAGE = 'testr', env))
}

WriteCapInfo_cpp <- function(fname) {
    invisible(.Call('testr_WriteCapInfo_cpp', PACKAGE = 'testr', fname))
}

