# Copyright (c) 2013, Purdue University. All rights reserved.
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
#
# This code is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 only, as
# published by the Free Software Foundation.
#
# This code is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# version 2 for more details (a copy is included in the LICENSE file that
# accompanied this code).
#
# You should have received a copy of the GNU General Public License version
# 2 along with this work; if not, write to the Free Software Foundation,
# Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
# or visit www.oracle.com if you need additional information or have any
# questions.

#' @title Test Case generator based on capture files
#'
#' @description This function works with the trace information generated by instrumented GNU-R. 
#' It is strictly oriented to that, please see readme for more information.
#'
#' @param root a directory containg capture information or capture file
#' @param output.dir directory where generated test cases will be saved
#' @param verbose wheater display debug output
#' @param use.get.anywhere whether to perform lookup for a closure in loaded namespaces
#' @export

TestGen <- function(root, output.dir, use.get.anywhere = TRUE, verbose=testrOptions('verbose')) {
  if (verbose) {
    cat("Output:", output.dir, "\n");
    cat("Root:", root, "\n");
  }
  
  if (missing(output.dir)) stop("A output directory must be provided!");
  if (!file.exists(output.dir) || !file.info(output.dir)$isdir)
    dir.create(output.dir)
  output.dir <<- output.dir

  if (!file.exists(root)) stop("Intermediate file doesn't exist!");
  bad.argv.file <<- file.path(output.dir, "bad_arguments", fsep=.Platform$file.sep);
  
  if (!file.exists(bad.argv.file) && !file.create(bad.argv.file)) stop("Unable to create file: ", bad.argv.file);
  
  if (file.info(root)$isdir){
    all.capture <- lapply(list.files(root, recursive=TRUE, all.files = TRUE), function(x) file.path(root,x))
  }else{
    all.capture <- root
  }
  cache$files <- list()
  Map(ProcessCapture, all.capture)
  for(f in cache$files) {
    close(cache$files[[f]])
  }
  rm(output.dir, envir = globalenv())
  rm(bad.argv.file, envir = globalenv())
}

#' @title Manage Test Case file
#'
#' @description This function creates a test case file if one does not exist already
#' @param path a directory containg capture information or capture file
#' @param name directory where generated test cases will be saved
#' @param cache environment for caching already created files
#' @seealso TestGen
EnsureTCFile <- function(path, name, cache) {
  tc.file <- cache$files[[name]];
  if (is.null(tc.file)) {
    name <- gsub(.Platform$file.sep, "sep", name);
    tc.file <- file.path(path, paste("tc_", name, ".r", sep=""), fsep=.Platform$file.sep);
    if (!file.exists(tc.file) && !file.create(tc.file)) stop("Unable to create file: ", tc.file);
  }
  return(tc.file);
}

ReadSymbolValues <- function(lines){
  k_sym <- 1
  k_value <- 1
  symb <- vector()
  vsym <- vector()
  symb[k_sym] <- ""
  vsym[k_value] <- ""
  while (StartsWith(kSymbPrefix, lines[cache$i])){
    symb[k_sym] <- paste(symb[k_sym], SubstrLine(lines[cache$i]), sep = "") 
    cache$i <- cache$i + 1
    k_sym <- k_sym + 1
    symb[k_sym] <- ""
    vsym[k_value] <- ReadValue(lines, kValSPrefix)
    k_value <- k_value + 1
    vsym[k_value] <- ""
  }
  length(symb) <- length(symb) - 1
  length(vsym) <- length(vsym) - 1
  return(list(symb, vsym))
}

ReadValue <- function(lines, prefix){
  value <- vector()
  j <- cache$i
  while (StartsWith(prefix, lines[j])){
    value <- c(value, SubstrLine(lines[j]))
    j <- j + 1
  }
  cache$i <- j
  return(paste(value, collapse="\n", sep=""))
}
#' @title Process File with Closure capture information
#'
#' @description This function parses file with closure capture information and generates test cases
#' @param capture.file path to closure capture file
#' @seealso TestGen GenClosureTC
ProcessCapture<- function(capture.file){
  lines <- readLines(capture.file)
  cache$i <- 1
  while (cache$i < length(lines)){
    symbol.values <- ReadSymbolValues(lines)
    symb <- symbol.values[[1]]
    vsym <- symbol.values[[2]]
    func <- ReadValue(lines, kFuncPrefix)
    body <- ReadValue(lines, kBodyPrefix)
    args <- ReadValue(lines, kArgsPrefix)
    warn <- ReadValue(lines, kWarnPrefix)
    retv <- ReadValue(lines, kRetvPrefix)
    errs <- ReadValue(lines, kErrsPrefix)
    cache$i <- cache$i + 1
    tc.file <- EnsureTCFile(output.dir, func, cache);
    feedback <- GenerateTC(symb, vsym, func, body, args, warn, retv, errs, use.get.anywhere = TRUE); # added symb and vsym
    #### see what we get
    if (feedback$'type' == "err") {
      #### the captured information is not usable
      write(feedback$'msg', file=bad.argv.file, append=TRUE);
    } else if (feedback$'type' == "src") {
      #### good, we get the source code
      write(feedback$'msg', file=tc.file, append=TRUE);
    } else {
      stop("Not reached!");
    }
  }
}

#' @title Generates a testcase for closure function
#'
#' @description This function generates a test case for builtin function using supplied arguments. All elements should be given as text.
#' @param symb symbols to be initialized before the call
#' @param vsym values of the symbols
#' @param func closure function name
#' @param body closure body
#' @param argv input arguments for a closure function call
#' @param warn expected warnings
#' @param retv expected return value
#' @param retv expected errors
#' @param use.get.anywhere whether to try to get body of the function in the loaded namespaces
#' @seealso TestGen ProcessClosure
GenerateTC<- function(symb, vsym, func, body, argv, warn, retv, errs, use.get.anywhere = TRUE) {
  # check to see if it is bad arguments
  ParseAndCheck <- function(what) {
    tryCatch({eval(parse(text=what)); TRUE}, warning=print, error=function(e){FALSE});
  }
  mk.err <- function(msg) { list(type="err", msg=msg); }
  mk.src <- function(msg) { list(type="src", msg=msg); }
  # check validity of symbol values
  invalid.symbols <- vector()
  if (length(symb) > 0 && symb[1] != ""){
    for (i in 1:length(vsym)){
      if (!ParseAndCheck(paste(symb[i], "<-", vsym[i], sep=" "))){
        invalid.symbols <- c(invalid.symbols, i)  
      }
    }
    if (length(invalid.symbols) != 0){
      symb <- symb[-invalid.symbols]
      vsym <- vsym[-invalid.symbols]
    }
  }
  # check validity of arguments
  valid.argv <- ParseAndCheck(argv)
  valid.retv <- ParseAndCheck(retv)
#   argv.obj <- ParseAndCheck(argv);
#   retv.obj <- ParseAndCheck(retv);
  
  # proper argument should always be packed in a list
  if (!valid.argv || !valid.retv) {
    return (mk.err(paste("func:", func, "\nbody:", body, "\nargv:", argv,"\nretv:", retv,"\n")));
  }  
  # TODO: potentially good arguments, alter it 
  #  argv.obj.lst <- alter.arguments(argv.obj);
  
  variables <- ""
  if (length(symb) > 0 && symb[1] != ""){
    for (i in 1:length(symb)){
      variables <- paste(variables, symb[i], "<-", vsym[i], "\n", sep=" ")
    }
  }
  call <- ""
  args <- length(eval(parse(text=argv)));
  if (body != ""){
    f.search <- utils::getAnywhere(func)
    if (is.list(f.search$objs) && length(f.search$objs) == 0 && !use.get.anywhere){
      if (ParseAndCheck(body)){
        call <- paste(func, "<-", body, "\n", sep="");
      } else {
        return (mk.err(paste("func:", func, "\nbody:", body, "\nargv:", argv,"\nretv:", retv,"\n")));
      }
    }else{
      call <- paste(func, "<-",  "utils::getAnywhere(",func,")[1]",";\n", sep="")
    }
  }
  if (args > 0) {
    call <- paste(call, "argv <- ", argv, "\n", sep="");
  } else {
    call <- paste(call, "argv <- list()", "\n", sep="");
  }
  if (grepl("`", func)){
    call <- paste(call, "do.call(", func, ", argv);", sep="");
  }else{ 
    call <- paste(call, "do.call('", func, "', argv);", sep="");
  }
  if (length(symb) > 0 && symb[1] != "")
    call <- paste(variables, call, sep=""); # added because of variables
  src <- ""
  src <- paste(src, "test(id=0, code={\n", call, "\n}, ", sep="")
  if (warn != "")
    src <- paste(src, 'w = ', warn, ",", sep = "")
  if (errs != "")
    src <- paste(src, 'e = ', deparse(errs), sep = "")
  else {
    src <- paste("expected <- ", retv, "\n", src, sep="");
    src <- paste(src, "o = expected")
  }
  src <- paste(src, ");\n", sep="")
  list(type="src", msg=src);
}

#' @title Removes prefixes and quote from line
#'
#' @description Used for processing capture file information. Deletes prefixes to get essential information
#' @param l input line
#' @seealso ProcessClosure
SubstrLine <- function(l){
  if (grepl("quote\\(", l)){
    ret.line <- strsplit(l, "\\(")[[1]][2];
    if (substr(ret.line, nchar(ret.line), nchar(ret.line)) == ")")
      ret.line <- substr(ret.line, 0, nchar(ret.line) - 1)
  }else{
    ret.line <- substr(l, 7, nchar(l));     
  }
  ret.line
}

StartsWith <- function(prefix, x)
  grepl(paste("^", prefix, sep=""), x)